### ISSUE TITLE
pipe-mysql's vim's functions are not defined in some environments

### ISSUE THREAD

**Issue by nolleh** [NLKNguyen/pipe-mysql.vim#9]
hello, 

when I check - command pipe(dependent plugin), It is well defined it's functions, 
but when check pipe-mysql, there isn't any commands..
so I am having trouble to use this awesome feature.

any I idea that enlighten you?
Thanx in advance!

my OS: Mac OS Monterey (12.3.1)

```bash
:verbose command Pipe
    Name              Args Address Complete    Definition
    Pipe              1            shellcmd    :call g:Pipe(<f-args>)
        Last set from ~/.vim/plugged/pipe.vim/plugin/pipe.vim line 73
    PipeLast          0                        :call g:PipeLast()
        Last set from ~/.vim/plugged/pipe.vim/plugin/pipe.vim line 186
    PipeToFile        ?            file        :call g:PipeToFile(<f-args>)
        Last set from ~/.vim/plugged/pipe.vim/plugin/pipe.vim line 53
    PipeToggleWindow  0                        :call g:PipeToggleWindow()
        Last set from ~/.vim/plugged/pipe.vim/plugin/pipe.vim line 348
    PipeUse           1                        :call g:PipeUse("<args>")
        Last set from ~/.vim/plugged/pipe.vim/plugin/pipe.vim line 32
Press ENTER or type command to continue

```

```bash
:verbose command PipeMySql
No user-defined commands found

```

plugin was installed successfully when I check my .vim/plugged

```bash
➜  pipe-mysql.vim git:(master) l
total 32
drwxr-xr-x   6 nolleh  staff   192B Dec 23 17:02 .
drwxr-xr-x  19 nolleh  staff   608B Dec 23 17:02 ..
drwxr-xr-x  13 nolleh  staff   416B Dec 23 21:55 .git
-rw-r--r--   1 nolleh  staff   1.1K Dec 23 17:02 LICENSE
-rw-r--r--   1 nolleh  staff   8.7K Dec 23 17:02 README.md
drwxr-xr-x   3 nolleh  staff    96B Dec 23 21:06 plugin
➜  pipe-mysql.vim git:(master)
```

**Comment by NLKNguyen** [comment]
Can you still use the default shortcuts as listed in the README of pipe-mysql?

I think the reason they didn't show when you ran `:verbose command PipeMySql` is simply because pipe-mysql.vim doesn't expose any commands It just provides global functions `g:PipeMySQL_*` that can be called anywhere in Vim, and it adds optional default key mappings onto the current SQL buffer/file.

https://github.com/NLKNguyen/pipe-mysql.vim/blob/5b9e80417d4e9f9d8b1312e73be337660aaedc94/plugin/pipe-mysql.vim#L369

Whereas, pipe.vim exposes the commands via `<Plug>` mappings, so they can be seen when you run `:verbose command Pipe`

https://github.com/NLKNguyen/pipe.vim/blob/df1b5036ae8781c34ad28391afdeacc87478ff8c/plugin/pipe.vim#L390

You can expose those function calls `:call g:PipeMySQL_*` as `<Plug>` commands in your .vimrc if you want to invoke PipeMySQL that way. I don't remember exactly why I didn't provide that interface as well, but back then I solely used the keyboard shortcuts.

You can read more about `<Plug>` explanation here https://stackoverflow.com/a/18547013

Hope it helps!

**Comment by nolleh** [comment]
Thanx a lot for your kind explanations. 
as long as I understands, it looks like the ``<Plug>`` mapping expose vim's functions. 

but after reading your comment,
I have more questions . :) 

1. acutally the very reason that want to find the function is, default shortcut is not worked in my environment.
when I type the ``<leader> rf``,`` <leader> dl``.. it dosen't worked as I expected (run mysql command), 
just worked as other vimcommand (for example, replacing character caused by 'r', or deleting character caused by 'd'

I don't know It will be helpful info, my environment is vim (not neovim)

if you want it to sperate the issue (cause to topic is already changed to exposing command ---> not working shortcut),  
let me know! 

thanx.

**Comment by NLKNguyen** [comment]
Does it work if you manually call the function in Vim command `:call g:PipeMySQL_RunFile()` ?

What key is your `<leader>`  mapped to? I mapped to coma key `,`, so I type `,rf` in Normal mode to automatically calls the above function.

I suspect the file type of your buffer is not recognized as mysql. Because the shortcuts are mapped to `mysql` file type only,  make sure your buffer has the correct file type. Check: `:set filetype?`

The typical `.sql` file extension can be recognized as some file type other than mysql by your vim default setting. If you only deal with MySQL, then one way you can do is to put in your .vimrc an autocommand that sets file type for any .sql buffer to be mysql.

`au BufRead,BufNewFile *.sql set filetype=mysql`

**Comment by nolleh** [comment]
oh!! you are right!

``: set filetype`` says on my file type as 'sql', so it didn't working!
after writing your snippet on my .vimrc, then it work as I expected!

thanx a lot, as you could've find out, I am newbie for vim, so this conversation has give me some knowleges.

I think the file type restriction is written in your doc, it will be good to users who have trouble like me.
